version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shiftstack-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shiftstack
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shiftstack-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    image: dpage/pgadmin4
    container_name: shiftstack-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shiftstack.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
