const AUDIT_ACTIONS = {
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  ACTIVATE_EMPLOYEE: "ACTIVATE_EMPLOYEE",
  DEACTIVATE_EMPLOYEE: "DEACTIVATE_EMPLOYEE",
  CHANGE_EMPLOYEE_ROLE: "CHANGE_EMPLOYEE_ROLE",
  RESET_EMPLOYEE_PASSWORD: "RESET_EMPLOYEE_PASSWORD",
};

module.exports = {
  AUDIT_ACTIONS,
};
